package tokens;

/**
 * Enumeración de los tipos de token para el compilador GoLite. 
 * Actualizado y afinado para cubrir la Fase 1 y 2 según requerimientos.
 */
public enum TipoToken {

    // --- LITERALES ---
    LIT_ENTERO, LIT_FLOTANTE, LIT_STRING, LIT_RUNE, LIT_BOOLEANO, LIT_NIL,
    
    // --- TIPOS PRIMITIVOS ---
    TIPO_INT, TIPO_FLOAT64, TIPO_STRING, TIPO_BOOL, TIPO_RUNE,
    
    // --- PALABRAS RESERVADAS: CONTROL DE FLUJO ---
    RES_IF, RES_ELSE, RES_FOR, RES_SWITCH, RES_CASE, RES_DEFAULT,
    RES_BREAK, RES_CONTINUE, RES_RETURN, RES_RANGE, RES_TYPE,
    
    // --- PALABRAS RESERVADAS: DECLARACIÓN ---
    RES_VAR, RES_FUNC, RES_STRUCT, RES_PACKAGE,
    
    // --- PALABRAS RESERVADAS: FUNCIONES EMBEBIDAS ---
    RES_FMT_PRINTLN, 
    RES_STRCONV_ATOI, 
    RES_STRCONV_PARSEFLOAT,
    RES_REFLECT_TYPEOF, 
    RES_APPEND, 
    RES_LEN, 
    RES_STRINGS_JOIN, 
    
    // --- IDENTIFICADOR ---
    IDENTIFICADOR,
    
    // --- OPERADORES ARITMÉTICOS ---
    OP_SUMA, OP_RESTA, OP_MULT, OP_DIV, OP_MOD,
    
    // --- OPERADORES DE ASIGNACIÓN ---
    OP_ASIGNACION, OP_ASIGN_CORTO, OP_ASIGN_SUMA, OP_ASIGN_RESTA,
    
    // --- OPERADORES DE COMPARACIÓN ---
    OP_IGUAL, OP_DIFERENTE, OP_MENOR, OP_MAYOR, OP_MENOR_IGUAL, OP_MAYOR_IGUAL,
    
    // --- OPERADORES LÓGICOS ---
    OP_AND, OP_OR, OP_NOT,
    
    // --- INCREMENTO / DECREMENTO ---
    OP_INCREMENTO, OP_DECREMENTO,
    
    // --- DELIMITADORES Y PUNTUACIÓN ---
    PAREN_ABRE, PAREN_CIERRA,
    LLAVE_ABRE, LLAVE_CIERRA,
    COR_ABRE, COR_CIERRA,
    PUNTO_COMA, DOS_PUNTOS, COMA, PUNTO,
    
    // --- ESPECIALES ---
    EOF, ERROR
}